"""empty message

Revision ID: 263e3265fc39
Revises: 7629809bbe2f
Create Date: 2023-08-19 14:17:37.609176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263e3265fc39'
down_revision = '7629809bbe2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('van', schema=None) as batch_op:
        batch_op.add_column(sa.Column('van_model', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('van', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('active')
        batch_op.drop_column('notes')
        batch_op.drop_column('van_model')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
