"""empty message

Revision ID: 7088928c9d52
Revises: 263e3265fc39
Create Date: 2023-08-19 15:20:00.760346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7088928c9d52'
down_revision = '263e3265fc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('van', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_battery_change_date', sa.Date(), nullable=True))
        batch_op.drop_column('last_battery_change_milage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('van', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_battery_change_milage', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_battery_change_date')

    # ### end Alembic commands ###
